### ISSUE TITLE
Passing arguments to included files

### ISSUE THREAD

**Issue by evandiamond** [Vishal0203/file-include-webpack-plugin#1]
Any idea if this feature will arrive soon? :)

**Comment by Vishal0203** [comment]
@evandiamond I haven't started working on that yet. Will work over the weekend. 
I'm ready to accept pull requests too! :)

**Comment by Vishal0203** [comment]
@evandiamond Passing arguments is supported in v1.0.9
I've also updated readme, regarding the usage. 

Closing this issue for now.

**Comment by evandiamond** [comment]
Wow, this is fantastic, thank you!
