### ISSUE TITLE
How to have script automatically injected into result

### ISSUE THREAD

**Issue by Cookizza** [Vishal0203/file-include-webpack-plugin#10]
Hello,

I am certain this is the type of plugin I want to easily include partial HTML files in my pages. 

However I am a bit lost on how to have this plugin automatically insert the script tags like the html-webpack-plugin does.

Should I be using both of these plugins? if so, how should I be configuring it?

Thanks!

**Comment by Vishal0203** [comment]
Ideally you shouldn't be using both the plugins, although there is no harm in doing so either. 
Could you please provide an example of what you're trying to achieve? 

I can extend the support / use case of this plugin.

**Comment by Vishal0203** [comment]
[L50](https://github.com/Vishal0203/file-include-webpack-plugin/blob/master/src/utils.js#L50) here is filtering all the other formats.

Note that this plugin doesn't generate an HTML output automatically, like other plugins. 
If you notice the example, `index.html` file is created by the developer and the plugin allows the developer to inject partials.

As a quick example (considering the directory structure of the projects example directory), 
If you want to inject `something.js` and `bootstrap.js` into my index.html. 
create a file in partials, say `base-scripts.html` with

```
<script src="./something.js"></script>
<script src="./bootstrap.js"></script>
```

and then include them in your `index.html` as `@@include('../partials/scripts/base-scripts.html')`
This will inject the script tags in your final html.

Let me know if that solves your problem.

**Comment by Cookizza** [comment]
Thanks for the information!
