### ISSUE TITLE
Ability to include partial multiple times

### ISSUE THREAD

**Issue by Monkeywiz** [Vishal0203/file-include-webpack-plugin#13]
If I want to use an html partial for a card in a grid for example I'd currently have to have markup for the entire grid the the partial.
It would be great if this worked more like gulp-file-include and you could instead include the card partial multiple times and passing different variables for each include

**Comment by Vishal0203** [comment]
@Monkeywiz  Please upgrade to v1.3.4 and try your scenario. It should be working now. 
Closing this issue, please reopen if it persists.
