### ISSUE TITLE
indent in html

### ISSUE THREAD

**Issue by AJIEKCEU** [Vishal0203/file-include-webpack-plugin#27]
after build, html has wrong indents. 
![image](https://user-images.githubusercontent.com/3834281/98934885-c8d53180-24f3-11eb-8165-30200850721f.png)
How to fix it?

**Comment by Vishal0203** [comment]
Is it needed? Generally we end-up minifying our html files, so it doesn't matter if the indent's are not okay in the build, in my opinion. Do let me know if there is any specific reason why you want this.

**Comment by AJIEKCEU** [comment]
my backend developers complain that it is very inconvenient to read the code, this is the main reason. If this can be fixed, I will be grateful, and if you do this please write.

**Comment by Vishal0203** [comment]
@AJIEKCEU Version 1.3.6 provides support to beautify the generated html.
Corresponding documentation here - https://github.com/Vishal0203/file-include-webpack-plugin#how-to-pass-custom-html-cleaner-options

**Comment by AJIEKCEU** [comment]
thanks so much! helped.
