### ISSUE TITLE
clean-html delete <script>

### ISSUE THREAD

**Issue by AJIEKCEU** [Vishal0203/file-include-webpack-plugin#31]
in the last update you added [clean-html](https://github.com/dave-kennedy/clean-html) and it turns out that it removes the tags `<scripts>` (((

**Comment by KaloyanMarinov** [comment]
I have the same problem

**Comment by Vishal0203** [comment]
I'll take a look right now.

**Comment by Vishal0203** [comment]
Thanks for reporting. 
Resolved in version 1.3.7
Please upgrade
